version: '3.9'

services:
  dev:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8888"
    volumes:
      - ./docs:/work
    command: ["bash", "-c", "source /etc/bash.bashrc && jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token='${JUPITER_TOKEN}'"]

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http dev:8888 --region jp --log=stdout
    tty: true
